/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YnZhong
 */
public class CartPage extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private CustomerClass customer;
    private Cart cart;
    private List<String> vList = new ArrayList<>();
    private String column[] = {"Food id", "Status", "Food Name", "Quantity", "Price"};
    private String vid;
    private double totalPrice = 0;
    private int row = 0;
    /**
     * Creates new form CartPage
     */
    public CartPage(CustomerClass customer) {
        initComponents();
        this.customer = customer;
        initialize();
        showCbox();
    }
    
    private void initialize(){
        lblName.setText(customer.getName());
        lblCreditBalance.setText(customer.getCreditBalance() + "");
    }
    
    private void showCbox(){
        cboxVendor.removeAllItems();
        vList = new ArrayList<>();
        CartList cList = new CartList(customer.getUsername());
        for (Cart c : cList.get()){
            VendorClass vc = new VendorClass(c.getVendorid());
            vList.add(c.getVendorid());
            cboxVendor.addItem(vc.getName());
        }
    }
    
    private void showTable(String vid){
        
        totalPrice = 0;
        tableFood.setModel(model);
        model.setRowCount(0);
        model.setColumnIdentifiers(column);
        cart = new Cart(customer.getUsername(), vid);
        for (Map.Entry<String, Integer> food : cart.getFood().entrySet()) {
            String key = food.getKey();
            Integer value = food.getValue();
            VendorMenu vm = new VendorMenu(vid, key);
            String[] rowData = {vm.getId(),vm.getStatus(), vm.getName(), value + "", vm.getPrice() + ""};
            model.addRow(rowData);
            totalPrice += (value*vm.getPrice());
        }
        lblTotalPrice.setText(totalPrice + "");
        tableFood.removeColumn(tableFood.getColumnModel().getColumn(0));
        tableFood.removeColumn(tableFood.getColumnModel().getColumn(0));
    }
    
    private void order(){
        OrderTransaction ot;
        
        switch (cboxOrderType.getSelectedIndex()){
            case 0 -> {
                DineInOrder dineIn = new DineInOrder(cart);
                dineIn.setTotalPrice(totalPrice);
                dineIn.place();
                ot = new OrderTransaction(customer.getUsername(), dineIn);
                ot.setOrder();
            }
            case 1 -> {
                TakeAwayOrder takeAway = new TakeAwayOrder(cart);
                takeAway.setTotalPrice(totalPrice);
                takeAway.place();
                ot = new OrderTransaction(customer.getUsername(), takeAway);
                ot.setOrder();
            }
            case 2 -> {
                DeliveryOrder delivery = new DeliveryOrder(cart, (String) cboxLocation.getSelectedItem());
                delivery.setTotalPrice(totalPrice);
                delivery.place();
                DeliveryTask dt = new DeliveryTask(delivery);
                dt.assign();
                Notification noti = new Notification(cart.getCustomerid(), cart.getVendorid(), "New Delivery Order by " + delivery.getCustomerid());
                noti.send();
                ot = new OrderTransaction(customer.getUsername(), delivery);
                ot.setOrder();
            }
            default -> {
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        cboxVendor = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFood = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDeduct = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        lblName2 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        cboxLocation = new javax.swing.JComboBox<>();
        lblName5 = new javax.swing.JLabel();
        cboxOrderType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cboxVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxVendorActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblName1.setText("Credit: RM");

        lblCreditBalance.setText("Name");

        lblName3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName3.setText("Cart");

        tableFood.setModel(model);
        jScrollPane1.setViewportView(tableFood);

        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDeduct.setText("-");
        btnDeduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeductActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnOrder.setText("Place Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        lblName2.setText("Total Price: RM");

        lblTotalPrice.setText("Name");

        lblName4.setText("Location: ");

        cboxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block A", "Block B", "Block C", "Block D", "Block E" }));

        lblName5.setText("Order Type: ");

        cboxOrderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine In", "Take Away", "Delivery" }));

        jLabel1.setText("Vendor: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblName1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(lblName4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(lblName5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cboxOrderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboxVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnDeduct))
                                    .addComponent(btnRemove)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnOrder)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName1)
                            .addComponent(lblCreditBalance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName4)
                            .addComponent(cboxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblName3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName5)
                            .addComponent(cboxOrderType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboxVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName2)
                            .addComponent(lblTotalPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnDeduct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrder))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        row = tableFood.getSelectedRow();
        String value = model.getValueAt(row, 0).toString();
        VendorMenu vm = new VendorMenu(vid, value);
        cart.add(vm);
        showTable(vid);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeductActionPerformed
        row = tableFood.getSelectedRow();
        String value = model.getValueAt(row, 0).toString();
        cart.deduct(value);
        showTable(vid);
    }//GEN-LAST:event_btnDeductActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        cart.delete();
        showCbox();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed

        if(customer.getCreditBalance()<totalPrice){
            JOptionPane.showMessageDialog(null, "Insufficient amount", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int option = JOptionPane.showConfirmDialog(null,
             "Confirm Order?", "Order confirmation", JOptionPane.YES_NO_OPTION);
            if(option == 0){
                order();
                cart.delete();
                this.customer = new CustomerClass(customer.getUsername());
                initialize();
                showCbox();
            }
        }
         
    }//GEN-LAST:event_btnOrderActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new CustomerHome(customer).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void cboxVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxVendorActionPerformed
        int index = cboxVendor.getSelectedIndex();
        model.setRowCount(0);
        if(index != -1){
            vid = vList.get(index);
            cart = new Cart(customer.getUsername(), vid);
            showTable(vid);
        }
    }//GEN-LAST:event_cboxVendorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeduct;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cboxLocation;
    private javax.swing.JComboBox<String> cboxOrderType;
    private javax.swing.JComboBox<String> cboxVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTable tableFood;
    // End of variables declaration//GEN-END:variables
}
