/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YnZhong
 */
public class MenuPage extends javax.swing.JFrame {

    private CustomerClass customer;
    private VendorClass vendor;
    private SearchVendor sv;
    DefaultTableModel model = new DefaultTableModel();
    private String []column = {"Foodid", "Food Name", "Describe", "Price"};
    /**
     * Creates new form MenuPage
     * @param customer A customer object of the customer user
     * @param vendor A vendor object of the searched vendor
     * @param sv Maintain the latest status of search vendor page
     */
    public MenuPage(CustomerClass customer, VendorClass vendor, SearchVendor sv) {
        initComponents();
        this.customer = customer;
        this.vendor = vendor;
        this.sv = sv;
        initialize();
        showTable();
    }
    
    private void initialize(){
        lblName.setText(customer.getName());
        lblCreditBalance.setText(customer.getCreditBalance() + "");
        lblVendorName.setText(vendor.getName());
    }
    
    private void showTable(){
        tableMenu.setModel(model);
        model.setColumnIdentifiers(column);
        try{
            for (Object obj : new VendorMenu().getAllMenu(vendor.getUsername())){
                VendorMenu vm = (VendorMenu) obj;
                String []column = {vm.getId(), vm.getName(), vm.getDescribe(), vm.getPrice()+""};
                model.addRow(column);
            }
            tableMenu.removeColumn(tableMenu.getColumnModel().getColumn(0));
        } catch(NullPointerException ex){
            System.out.println("No menu found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        lblVendorName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lblName.setText("Name");

        jLabel2.setText("Credit: RM");

        lblCreditBalance.setText("123");

        lblVendorName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVendorName.setText("Vendor Name");

        tableMenu.setModel(model);
        tableMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMenuMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblVendorName)))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCreditBalance)
                    .addComponent(lblVendorName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMenuMouseReleased
//        getting the line index of the food, get foodid, append into cart
        int column = 0;
        int row = tableMenu.getSelectedRow();
        String value = model.getValueAt(row, column).toString();
        Cart c = new Cart(customer.getUsername(), vendor.getUsername());
        VendorMenu vm = new VendorMenu(vendor.getUsername(), value);
        c.add(vm);
    }//GEN-LAST:event_tableMenuMouseReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        sv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblVendorName;
    private javax.swing.JTable tableMenu;
    // End of variables declaration//GEN-END:variables
}
