/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YnZhong
 */
public class NotificationPage extends javax.swing.JFrame {

    private CustomerClass customer;
    private List<Notification> notiList = new ArrayList<>();
    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"Notification id", "Sender", "Date Time", "Message"};
    
    /**
     * Creates new form NotificationPage
     */
    public NotificationPage(CustomerClass customer) {
        initComponents();
        this.customer = customer;
        initialize();
        showTable();
    }
    private void initialize(){
        
        lblName.setText(customer.getName());
        lblCreditBalance.setText(customer.getCreditBalance() + "");
        NotificationList nl = new NotificationList();
        for(Notification noti : nl.getAll()){
            if (noti.getRecepient().getUsername().equals(customer.getUsername()))
                notiList.add(noti);
        }
    }
    
    private void showTable(){
        tableNotification.setModel(model);
        model.setRowCount(0);
        model.setColumnIdentifiers(column);
        for(Notification noti : notiList){
             String[] rowData = {noti.getNotificationid(), noti.getSender().getName(), noti.getDateTime(), noti.getMessage()};
             model.addRow(rowData);
        }
        tableNotification.removeColumn(tableNotification.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNotification = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Notification");

        lblName.setText("Name");

        jLabel3.setText("Credit: RM");

        lblCreditBalance.setText("123");

        tableNotification.setModel(model);
        tableNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableNotificationMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableNotification);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditBalance)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCreditBalance)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new CustomerHome(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void tableNotificationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNotificationMouseReleased
        int row = tableNotification.getSelectedRow();
        String value = model.getValueAt(row, 0).toString();
        Notification noti = new Notification(value);
        noti.delete();
        showTable();
    }//GEN-LAST:event_tableNotificationMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tableNotification;
    // End of variables declaration//GEN-END:variables
}
