/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YnZhong
 */
public class OrderDetails extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"Status", "Food Name", "Quantity", "Price"};
    private Order order;
    private Cart cart;
    private CustomerClass customer;
    private VendorClass vendor;
    private double totalPrice;
    /**
     * Creates new form OrderDetails
     */
    public OrderDetails(Order order) {
        initComponents();
        this.order = order;
        initialize();
        showTable();
    }
    
    private void initialize(){
        this.cart = order.getCart();
        this.customer = new CustomerClass(cart.getCustomerid());
        this.vendor = new VendorClass(cart.getVendorid());
        lblLocationWord.setVisible(false);
        lblLocation.setVisible(false);
        lblName.setText(customer.getName());
        lblVendor.setText(vendor.getName());
        lblCreditBalance.setText(customer.getCreditBalance() + "");
        lblDateTime.setText(order.getDateTime());
        if(order.getOrderType().equals("Delivery")){
            DeliveryOrder deliOrder = (DeliveryOrder) order;
            lblLocationWord.setVisible(true);
            lblLocation.setVisible(true);
            lblLocation.setText(deliOrder.getLocation());
        }
            
        
    }
    
    private void showTable(){
        totalPrice = 0;
        tableOrderDetail.setModel(model);
        model.setColumnIdentifiers(column);
        model.setRowCount(0);
        for (Map.Entry<String, Integer> food : cart.getFood().entrySet()) {
            String key = food.getKey();
            Integer value = food.getValue();
            VendorMenu vm = new VendorMenu(cart.getVendorid(), key);
            String[] rowData = {vm.getStatus(), vm.getName(), value + "", vm.getPrice() + ""};
            model.addRow(rowData);
            totalPrice += (value*vm.getPrice());
        }
        lblTotalPrice.setText(totalPrice + "");
        tableOrderDetail.removeColumn(tableOrderDetail.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrderDetail = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblVendor = new javax.swing.JLabel();
        lblLocationWord = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        btnReorder = new javax.swing.JButton();
        lblTotalPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tableOrderDetail.setModel(model);
        jScrollPane1.setViewportView(tableOrderDetail);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Order Detail");

        lblName.setText("Name");

        jLabel3.setText("Credit: RM");

        lblCreditBalance.setText("123");

        jLabel5.setText("Date Time:");

        lblDateTime.setText("date time");

        jLabel7.setText("Vendor: ");

        lblVendor.setText("vendor name");

        lblLocationWord.setText("Location: ");

        lblLocation.setText("Location");

        btnReorder.setText("Reorder");
        btnReorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReorderActionPerformed(evt);
            }
        });

        lblTotalPrice.setText("jLabel2");

        jLabel4.setText("Total Price: RM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnReorder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalPrice)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVendor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDateTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLocationWord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLocation)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblCreditBalance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblVendor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblDateTime)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblLocationWord)
                                .addComponent(lblLocation)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnReorder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPrice)
                            .addComponent(jLabel4))))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReorderActionPerformed
        Cart c = new Cart(cart);
        c.add();
    }//GEN-LAST:event_btnReorderActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new OrderHistory(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReorder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLocationWord;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblVendor;
    private javax.swing.JTable tableOrderDetail;
    // End of variables declaration//GEN-END:variables
}
