/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YnZhong
 */
public class OrderHistory extends javax.swing.JFrame {

    private CustomerClass customer;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"Order id", "Vendor Name", "Order Type", "Total Price", "Status", "Date"};
    private int row = 0;
    
    /**
     * Creates new form OrderHistory
     */
    public OrderHistory(CustomerClass customer) {
        initComponents();
        this.customer = customer;
        initialize();
        showTable();
    }
    
    private void initialize(){
        lblName.setText(customer.getName());
        lblCreditBalance.setText(customer.getCreditBalance() + "");
        
    }
    
    private void showTable(){
        tableOrderHistory.setModel(model);
        model.setRowCount(0);
        model.setColumnIdentifiers(column);
        OrderList oList = new OrderList(customer.getUsername());
        for(Order o : oList.get()){
            Cart c = o.getCart();
            VendorClass vc = new VendorClass(c.getVendorid());
            String[] rowData = {o.getOrderid(), vc.getName(), o.getOrderType(), o.getTotalPrice() + "", o.getOrderStatus(), o.getDateTime()};
            model.addRow(rowData);
        }
        tableOrderHistory.removeColumn(tableOrderHistory.getColumnModel().getColumn(0));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrderHistory = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tableOrderHistory.setModel(model);
        jScrollPane1.setViewportView(tableOrderHistory);

        lblName.setText("Name");

        jLabel2.setText("Credit: RM");

        lblCreditBalance.setText("123");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Order History");

        btnCart.setText("View Food");
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCreditBalance)))
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnCart)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblCreditBalance)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCart)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new CustomerHome(customer).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        row = tableOrderHistory.getSelectedRow();
        String value = model.getValueAt(row, 0).toString();
        String type = model.getValueAt(row, 2).toString();
        Order order;
        if(type.equals("DineIn")){
            order = new DineInOrder(value);
            new OrderDetails(order).setVisible(true);
        }
        else if(type.equals("TakeAway")){
            order = new TakeAwayOrder(value);
            new OrderDetails(order).setVisible(true);
        }
        else if(type.equals("Delivery")){
            order = new DeliveryOrder(value);
            new OrderDetails(order).setVisible(true);
        }
        else
            System.out.println("Not valid order type");
        
        
        
    }//GEN-LAST:event_btnCartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tableOrderHistory;
    // End of variables declaration//GEN-END:variables
}
