/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YnZhong
 */
public class ReviewHistory extends javax.swing.JFrame {
    
    private CustomerClass customer;
    private ReviewList rList;
    private Review review;
    private DefaultTableModel model = new DefaultTableModel();
    private String[] column = {"Vendor id", "Vendor Name", "Date Time", "Review"};
    private int row = -1;
    /**
     * Creates new form ReviewHistory
     */
    public ReviewHistory(CustomerClass customer) {
        initComponents();
        this.customer = customer;
        initialize();
        showTable();
    }
    
    private void initialize(){
        rList = new ReviewList(customer.getUsername());
        lblName.setText(customer.getName());
        lblCreditBalance.setText(customer.getCreditBalance() + "");
    }
    
    private void showTable(){
        tableReviewHistory.setModel(model);
        model.setRowCount(0);
        model.setColumnIdentifiers(column);
        for(Object obj : rList.getAll()){
            Review r = (Review) obj;
            if(r.getReceiverid().startsWith("VD")){
                VendorClass vendor = new VendorClass(r.getReceiverid());
                String[] rowData = {vendor.getUsername(), vendor.getName(), r.getDateTime(), r.getReview()};
                model.addRow(rowData);
            }
            else{
                RunnerClass runner = new RunnerClass(r.getReceiverid());
                String[] rowData = {runner.getUsername(), runner.getName(), r.getDateTime(), r.getReview()};
                model.addRow(rowData);
            }
        }
        tableReviewHistory.removeColumn(tableReviewHistory.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableReviewHistory = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEditReview = new javax.swing.JButton();
        btnDeleteReview = new javax.swing.JButton();
        txtReview = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tableReviewHistory.setModel(model);
        tableReviewHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableReviewHistoryMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableReviewHistory);

        lblName.setText("Name");

        lblName1.setText("Credit: RM");

        lblCreditBalance.setText("Name");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Review History");

        btnEditReview.setText("Edit");
        btnEditReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditReviewActionPerformed(evt);
            }
        });

        btnDeleteReview.setText("Delete");
        btnDeleteReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtReview, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditReview, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeleteReview, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName1)
                    .addComponent(lblCreditBalance)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditReview)
                    .addComponent(txtReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteReview)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReviewActionPerformed
        row = tableReviewHistory.getSelectedRow();
        String receiverid = model.getValueAt(row, 0).toString();
        Review review = new Review(customer.getUsername(), receiverid);
        review.delete();
        showTable();
    }//GEN-LAST:event_btnDeleteReviewActionPerformed

    private void tableReviewHistoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReviewHistoryMouseReleased
        int row = tableReviewHistory.getSelectedRow();
        review = new Review(customer.getUsername(), (String) tableReviewHistory.getValueAt(row, 0));
    }//GEN-LAST:event_tableReviewHistoryMouseReleased

    private void btnEditReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditReviewActionPerformed
        row = tableReviewHistory.getSelectedRow();
        String receiverid = model.getValueAt(row, 0).toString();
        Review review = new Review(customer.getUsername(), receiverid);
        review.edit(txtReview.getText());
        showTable();
    }//GEN-LAST:event_btnEditReviewActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new CustomerHome(customer).setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteReview;
    private javax.swing.JButton btnEditReview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTable tableReviewHistory;
    private javax.swing.JTextField txtReview;
    // End of variables declaration//GEN-END:variables
}
