/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author YnZhong
 */
public class TrackOrder extends javax.swing.JFrame {

    private CustomerClass customer;
    private Order order;
    private List<Order> orderList = new ArrayList<>();
    /**
     * Creates new form TrackOrder
     */
    public TrackOrder(CustomerClass customer) {
        initComponents();
        this.customer = customer;
        initialize();
        showCBox();
    }
    
    private void initialize(){
        lblRunner.setVisible(false);
        lblRunnerStatus.setVisible(false);
        lblRunner.setText("");
        lblRunnerStatus.setText("Pending");
        lblLocationWord.setVisible(false);
        lblLocation.setVisible(false);
        lblName.setText(customer.getName());
        lblCreditBalance.setText(customer.getCreditBalance() + "");
    }
    
    private void showCBox(){
        cboxOrder.removeAllItems();
        OrderList oList = new OrderList(customer.getUsername());
        if(!oList.get().isEmpty()){
            for(Order o : oList.get()){
                VendorClass vc = new VendorClass(o.getVendorid());
                orderList.add(o);
                cboxOrder.addItem(vc.getName());
            }
        }
    }
    
    
    
    private void checkRunnerStatus(){
        String type = order.getOrderType();
        if(type.equals("Delivery")){
            DeliveryOrder o = (DeliveryOrder) order;
            lblLocationWord.setVisible(true);
            lblLocation.setVisible(true);
            lblRunner.setVisible(true);
            lblRunner.setText("Runner: ");
            lblRunnerStatus.setVisible(true);
            lblLocation.setText(o.getLocation());
            
            String status = o.getRunnerStatus();
            DeliveryTask dt = new DeliveryTask(o);
            if(o.getRunnerid() != null || dt.getTaskStatus() != null){
                lblRunnerStatus.setText(o.getRunnerStatus());
                lblRunner.setText(o.getRunnerid());
            }
            else if(status.equals("Waiting for pickup")){
                lblRunnerStatus.setText("Waiting for pickup");
            }
            else if(status.equals("Delivery Complete")){
                lblRunnerStatus.setText("Completed");
            }
        }
        else{
            lblRunnerStatus.setText("Pending");
        }
    }
    
    
    private void checkVendorStatus(){
        String status = order.getOrderStatus();
        System.out.println(order.getOrderStatus());
        if(status.equals("Preparing")){
            lblVendorStatus.setText("Preparing");
        }
        else if(status.equals("Wait to take")){
            lblVendorStatus.setText("Completed");
        }
        else{
            lblVendorStatus.setText("Pending");
        }
    }
    
    private boolean checkCancel(){
        return !lblVendorStatus.equals("Pending") || !lblRunnerStatus.equals("Pending");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboxOrder = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblOrderType = new javax.swing.JLabel();
        lblLocationWord = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRunner = new javax.swing.JLabel();
        lblVendorStatus = new javax.swing.JLabel();
        lblRunnerStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblName.setText("Name");

        jLabel1.setText("Credit: RM");

        lblCreditBalance.setText("123");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Track Order");

        cboxOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxOrderActionPerformed(evt);
            }
        });

        jLabel3.setText("Order Type: ");

        lblOrderType.setText("jLabel4");

        lblLocationWord.setText("Location: ");

        lblLocation.setText("Block A");

        jLabel4.setText("Vendor: ");

        lblRunner.setText("Runner: ");

        lblVendorStatus.setText("Status");

        lblRunnerStatus.setText("Status");

        jLabel5.setText("Price: RM");

        lblTotalPrice.setText("123");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOrderType))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRunner)
                                        .addGap(2, 2, 2))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblVendorStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRunnerStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLocationWord)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnCancel)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lblOrderType)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblCreditBalance))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblVendorStatus))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRunner)
                            .addComponent(lblRunnerStatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocationWord)
                            .addComponent(lblLocation))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblTotalPrice))))
                .addGap(19, 19, 19)
                .addComponent(btnCancel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new CustomerHome(customer).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void cboxOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxOrderActionPerformed
        int index = cboxOrder.getSelectedIndex();
        if(index >= 0){
            initialize();
            order = orderList.get(index);
            lblOrderType.setText(order.getOrderType());
            lblTotalPrice.setText(order.getTotalPrice() + "");
            checkVendorStatus();
            checkRunnerStatus();
        }
    }//GEN-LAST:event_cboxOrderActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int index = cboxOrder.getSelectedIndex();
        if(checkCancel()){
            order = orderList.get(index);
            order.cancel();
            JOptionPane.showMessageDialog(null, "Order deleted", "Order cancelation", JOptionPane.OK_OPTION);
            this.setVisible(false);
            new TrackOrder(customer).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Order is being accepted already");
        }
    }//GEN-LAST:event_btnCancelActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cboxOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLocationWord;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JLabel lblRunner;
    private javax.swing.JLabel lblRunnerStatus;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblVendorStatus;
    // End of variables declaration//GEN-END:variables
}
